version: '3.8'
services:
  postgresql:
    image: postgres:15
    container_name: postgres-spring-boot
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres.data:/var/lib/postgresql/data